### ISSUE TITLE
paragraph() got an unexpected keyword argument 'jc'

### ISSUE THREAD

**Issue by TheFlatline** [etfre/oodocx#2]
While using the table() function i encountered the stated error.
The statement causing it is in line 957:
cell.append(paragraph(h, jc='center'))

is jc=center a legacy call? The paragraph() function signature doesn't have that parameter, but it is still present in the function documentation.

**Comment by TheFlatline** [comment]
Note: wrapping the text of a cell in an oodocx.paragraph works as a workaround (the table() function, if provided with paragraphs, doesnt try to convert the text to a paragraph using the wrong function signature)

**Comment by etfre** [comment]
Yeah, jc is an old parameter that was removed due to redundancy when I put in the pprops and rprops parameters in the paragraph function. I'll admit that table is the primary function that I've been neglecting, and I just hadn't tested it since I made that change. The latest commit should be working, although I suspect that the table function is due for refactoring at some point in the future.
