### ISSUE TITLE
Applying styles to paragraphs

### ISSUE THREAD

**Issue by ajmirsky** [etfre/oodocx#4]
when creating an oodocx.paragraph it seems the `style` parameter isn't used any longer, so i tried adding it using `pprops={'pstyle':{'val':'Heading1'}}` but that doesn't seem to work either. The xml around a paragraph generated from oodocx vs python-docx vs. saved from word all look pretty much the same.

Is there a better way of applying a style?

**Comment by etfre** [comment]
It looks like you're running into a capitalization error. `pprops={'pStyle':{'val':'Heading1'}}` should work. You can also create the paragraph and then call `modify_paragraph(paragraph, pstyle="Heading1")`. I dropped the `style` parameter because it seemed to be redundant with rprops and pprops, but if styles are used commonly enough to justify their own parameter, I would be completely amenable to putting it back in.

**Comment by ajmirsky** [comment]
appreciate the suggestions! I was able to get it working with existing styles in the docx template that comes with oodocx.

yes, agreed. the `style` parameter is redundant now that there is `rpops` and `pprops`.

any thoughts on the best way to create a docx with custom styles? I tried to update the `styles.xml` in the oodocx template but that didn't work; I imagine there are dependencies in other files which probably need to be updated as well. Instead, I created a "blank" docx with the custom styles, opened it, appended paragraphs to its body and then saved the new file. All the style information seems to get carried forward from the original "blank" docx, with the exception of custom style hot-keys. I'll open up a separate issue on this if it'd be helpful. Haven't had chance to investigate where they live/belong and see what the fix might be.

Really appreciate your work on this library, big help. Anything I can do to contribute? create more documentation? functionality to add styles dynamically, as it looks like you started that with `add_style`? will definitely create a pull request if I track down where the hot-keys are disappearing to.

and, of course, happy new year : )

**Comment by etfre** [comment]
The program should only read from template files when you're creating a Docx "from scratch," and I would like to reach a point where every initial file necessary to create a new Docx is generated programatically. That shouldn't be too difficult using `etree.fromstring`; it just isn't something that I've gotten around to doing. Otherwise, if you're loading a Docx, the `__init__` method will read that Docx's file contents and use those instead, including styles.xml. I'm also planning on adding `pPr` and `rPr` parameters to the `add_style` method to make creating styles slightly less painful. It looks like the best solution for creating "new" documents with preset styles is what you're already doing -- loading a Docx that is completely blank except for a customized styles.xml file.

I'll admit that I'm not entirely sure what you're referring to with hot-keys. Perhaps you can bring that up in another issue?

And yes, anything that you would like to contribute would be immensely appreciated! The "big project" that is on my eventual to-do list is to add support for footnotes/endnotes etc, which is tricky primarily due to the fact that you need to interact with separate .xml files as well as keep track of ID numbers, similarly to images and comments. Beyond that, adding additional miscellaneous functionality, refactoring, debugging, and (especially) writing documentation would all be fantastic ways to contribute. Thanks for your interest in the project, and I'm looking forward to hearing from you more.

Happy 2014!
